---
- name: Ensure local ~/.ssh directory exists.
  file:
    path: ~/.ssh
    state: directory
    mode: 0700
  delegate_to: 127.0.0.1
  become: no

- name: Ensure local ~/.ssh/config file exists.
  file:
    path: ~/.ssh/config
    state: file
    mode: 0600
  delegate_to: 127.0.0.1
  become: no

- name: Add host entry to local ~/.ssh/config
  blockinfile:
    dest: ~/.ssh/config
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{ vagrant_machine_name }}"
    block: |
      Host {{ vagrant_hostname }}
        StrictHostKeyChecking no
        IdentityFile ~/.vagrant.d/insecure_private_key
        ForwardAgent yes
  delegate_to: 127.0.0.1
  become: no
